### ISSUE TITLE
是不是不支持win11

### ISSUE THREAD

**Issue by spvycf** [44vogan/Pixel-Robot#3]
是不是不支持win11？win11安装完打开闪退。

**Comment by spvycf** [comment]
win10下面我打开也是闪退，是需要安装什么环境嘛？为啥直接close不回复一下呢。。。。。。

**Comment by 44vogan** [comment]
不需要安装环境，用的是windows自带的api。

**Comment by 44vogan** [comment]
管理员模式打开试试

**Comment by spvycf** [comment]
不行，管理员，兼容性都试过了，打开就闪退。。。有没有日志什么的可以看？

**Comment by 44vogan** [comment]
没有做本地日志，你可以试试0.3.0版本中新上传的.exe文件。。。
