### ISSUE TITLE
多动作规则用不了了

### ISSUE THREAD

**Issue by XiaoWenMiao** [44vogan/Pixel-Robot#6]
本来用0.4.0没什么问题，看到0.4.2更新就修了点bug就没更新，然后0.5.0出了我想要的功能就更新了一下，没想到我原本长达46条动作的规则用不了了

**Comment by 44vogan** [comment]
0.5跟0.4储存数据的格式不一样了，没料到造成这个麻烦。安装的时候没有删除数据的话，0.4版本的规则在安装0.4客户端后应该还在，只能截图抄一下了，抱歉。

**Comment by XiaoWenMiao** [comment]
> 0.5跟0.4储存数据的格式不一样了，没料到造成这个麻烦。安装的时候没有删除数据的话，0.4版本的规则在安装0.4客户端后应该还在，只能截图抄一下了，抱歉。

按你说的一个个重新抄了一遍，确实可以用了，但是似乎发现了新增的规则休眠的问题
规则休眠不是检测成功后立刻停止对这个规则的检测，而是这个规则执行完后才会进入休眠
比如说，100ms的检测间隔，4500ms的延迟动作，因为规则休眠不是立刻停止检测的原因会在4500ms内被间隔为100ms的检测进行持续检测，最后这个时间内检测成功的规则会一股脑的同时执行
原本我预想的规则休眠是该规则被检测成功后立马停止对该规则的检测，而不是执行完后再停止

**Comment by 44vogan** [comment]
明白

**Comment by XiaoWenMiao** [comment]
> 明白

又发现了新的问题，今天醒了之后因为凌晨游戏维护，游戏自动退出了，px robot可能是因为一直检测不到东西就崩溃了，崩溃了之后原本能用的规则突然就用不了了，昨天刚抄的，今天因为崩溃又得重新抄一遍才能用，估计是崩溃的时候数据保存出错了

**Comment by XiaoWenMiao** [comment]
> > 明白
> 
> 又发现了新的问题，今天醒了之后因为凌晨游戏维护，游戏自动退出了，px robot可能是因为一直检测不到东西就崩溃了，崩溃了之后原本能用的规则突然就用不了了，昨天刚抄的，今天因为崩溃又得重新抄一遍才能用，估计是崩溃的时候数据保存出错了

又发现一个，似乎规则休眠不会被软件的stop给中断掉
如果在规则休眠的时间内反复start stop会导致规则休眠互相冲突，之前还没结束的规则休眠会继续在下一次start里面休眠，然后导致刚进入休眠的规则，在本该休眠的时间内因为上个未结束的休眠结束后再次被检测，除非调试的时候等到上一次规则休眠结束再start
